project_id = "ukpuhoynrqobqtzdbysp"

[functions.database-backup]
verify_jwt = true

[functions.database-restore]
verify_jwt = true

[functions.selective-restore]
verify_jwt = true

[functions.surgical-restore]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-dispatcher]
verify_jwt = false
