import { useQuery } from "@tanstack/react-query";
import { Link as RouterLink } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { formatCurrency } from "@/lib/mock-data";
import { formatDatePT } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { ExternalLink, Sparkles } from "lucide-react";

const TAG_LABEL: Record<string, string> = {
  bebidas: "Bebidas",
  comida: "Comida",
  higiene: "Higiene e Consumíveis",
  equipa: "Equipa Camarim",
  outros: "Outros",
};

const ORIGIN_LABEL: Record<string, string> = {
  advance: "Adiantamento",
  card: "Cartão",
  out_of_pocket: "Reembolso",
};

interface Props {
  transactionId: string;
}

/**
 * Read-only Camarim tab shown inside TransactionEditModal when the transaction
 * was generated by the consolidated camarim integration. Lists every camarim
 * item linked to the transaction, with analytical tags, supplier and amounts.
 */
export function TransactionCamarimTab({ transactionId }: Props) {
  const { data, isLoading } = useQuery({
    queryKey: ["transaction-camarim-items", transactionId],
    queryFn: async () => {
      const { data: items, error } = await supabase
        .from("camarim_items")
        .select(
          "id, session_id, supplier_name_raw, document_number, document_date, service_description, base_amount, iva_amount, total_amount, currency, payment_origin, analytic_tag, has_document, approved_without_document",
        )
        .eq("transaction_id", transactionId)
        .order("document_date", { ascending: true });
      if (error) throw error;
      if (!items || items.length === 0) return null;

      const sessionId = items[0].session_id as string;
      const { data: session } = await supabase
        .from("camarim_sessions")
        .select("id, title, mode, status, opened_at, closed_at, integrated_at, master_event_id")
        .eq("id", sessionId)
        .single();

      return { items, session };
    },
  });

  if (isLoading) {
    return <p className="text-sm text-muted-foreground">A carregar dados do camarim…</p>;
  }

  if (!data) {
    return (
      <div className="rounded-lg border border-border bg-muted/30 p-4 text-sm text-muted-foreground">
        Esta transação não está vinculada a uma sessão de Camarim.
      </div>
    );
  }

  const { items, session } = data as any;
  const total = items.reduce((s: number, i: any) => s + Number(i.total_amount ?? 0), 0);
  const totalBase = items.reduce((s: number, i: any) => s + Number(i.base_amount ?? 0), 0);
  const totalIva = items.reduce((s: number, i: any) => s + Number(i.iva_amount ?? 0), 0);

  // Aggregate by analytic tag
  const tagAgg = new Map<string, { count: number; total: number }>();
  for (const it of items) {
    const tag = it.analytic_tag ?? "outros";
    const cur = tagAgg.get(tag) ?? { count: 0, total: 0 };
    cur.count += 1;
    cur.total += Number(it.total_amount ?? 0);
    tagAgg.set(tag, cur);
  }
  const tagsSorted = Array.from(tagAgg.entries()).sort((a, b) => b[1].total - a[1].total);

  return (
    <div className="space-y-4">
      {/* Session header */}
      <div className="glass rounded-lg p-3 flex items-start justify-between gap-3">
        <div>
          <div className="flex items-center gap-2 text-xs text-muted-foreground uppercase tracking-wider">
            <Sparkles className="h-3.5 w-3.5" />
            Sessão de Camarim
          </div>
          <p className="mt-1 text-sm font-semibold">{session?.title ?? "—"}</p>
          <p className="text-xs text-muted-foreground mt-0.5">
            {session?.opened_at ? `Aberta ${formatDatePT(session.opened_at)}` : ""}
            {session?.integrated_at ? ` · Integrada ${formatDatePT(session.integrated_at)}` : ""}
          </p>
        </div>
        {session?.id && (
          <RouterLink
            to={`/camarim/${session.id}`}
            className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline"
          >
            Abrir sessão <ExternalLink className="h-3 w-3" />
          </RouterLink>
        )}
      </div>

      {/* Totals */}
      <div className="grid grid-cols-3 gap-2">
        <div className="rounded-lg border border-border bg-background/50 p-3">
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground">Base</p>
          <p className="text-sm font-mono font-semibold">{formatCurrency(totalBase)}</p>
        </div>
        <div className="rounded-lg border border-border bg-background/50 p-3">
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground">IVA</p>
          <p className="text-sm font-mono font-semibold">{formatCurrency(totalIva)}</p>
        </div>
        <div className="rounded-lg border border-primary/30 bg-primary/5 p-3">
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground">Total</p>
          <p className="text-sm font-mono font-semibold text-primary">{formatCurrency(total)}</p>
        </div>
      </div>

      {/* Tags breakdown */}
      {tagsSorted.length > 0 && (
        <div>
          <p className="text-xs font-medium text-muted-foreground mb-1.5">Por tag analítica</p>
          <div className="flex flex-wrap gap-1.5">
            {tagsSorted.map(([tag, v]) => (
              <Badge key={tag} variant="secondary" className="text-xs">
                {TAG_LABEL[tag] ?? tag}: {formatCurrency(v.total)} <span className="opacity-60 ml-1">({v.count})</span>
              </Badge>
            ))}
          </div>
        </div>
      )}

      {/* Items list */}
      <div>
        <p className="text-xs font-medium text-muted-foreground mb-1.5">
          Itens consolidados ({items.length})
        </p>
        <div className="rounded-lg border border-border overflow-hidden">
          <div className="max-h-[320px] overflow-y-auto">
            <table className="w-full text-xs">
              <thead className="bg-muted/50 sticky top-0">
                <tr className="text-left">
                  <th className="px-2 py-1.5 font-medium">Data</th>
                  <th className="px-2 py-1.5 font-medium">Fornecedor / Doc</th>
                  <th className="px-2 py-1.5 font-medium">Tag</th>
                  <th className="px-2 py-1.5 font-medium text-right">Base</th>
                  <th className="px-2 py-1.5 font-medium text-right">IVA</th>
                  <th className="px-2 py-1.5 font-medium text-right">Total</th>
                </tr>
              </thead>
              <tbody>
                {items.map((it: any) => (
                  <tr key={it.id} className="border-t border-border/50">
                    <td className="px-2 py-1.5 whitespace-nowrap text-muted-foreground">
                      {it.document_date ? formatDatePT(it.document_date) : "—"}
                    </td>
                    <td className="px-2 py-1.5">
                      <p className="font-medium">{it.supplier_name_raw ?? "—"}</p>
                      <p className="text-[10px] text-muted-foreground">
                        {it.document_number ? `Nº ${it.document_number}` : "(sem nº)"}
                        {it.service_description ? ` · ${it.service_description}` : ""}
                        {!it.has_document && (
                          <span className="ml-1 text-warning">· sem documento</span>
                        )}
                      </p>
                    </td>
                    <td className="px-2 py-1.5">
                      {it.analytic_tag ? (
                        <Badge variant="outline" className="text-[10px]">
                          {TAG_LABEL[it.analytic_tag] ?? it.analytic_tag}
                        </Badge>
                      ) : (
                        <span className="text-[10px] text-muted-foreground">—</span>
                      )}
                    </td>
                    <td className="px-2 py-1.5 text-right font-mono">{formatCurrency(Number(it.base_amount))}</td>
                    <td className="px-2 py-1.5 text-right font-mono">{formatCurrency(Number(it.iva_amount))}</td>
                    <td className="px-2 py-1.5 text-right font-mono font-semibold">
                      {formatCurrency(Number(it.total_amount))}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <p className="text-[10px] text-muted-foreground italic">
        Origem do pagamento: {ORIGIN_LABEL[items[0].payment_origin] ?? items[0].payment_origin}.
        Categoria contabilística forçada para 2.6.04 — Camarins. Detalhe analítico preservado por item.
      </p>
    </div>
  );
}
