import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SearchableSelect } from "@/components/ui/searchable-select";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { toast } from "@/hooks/use-toast";
import { Plus, Link2, Unlink } from "lucide-react";

interface Props {
  transactionId: string;
  defaultEmployeeName?: string;
  onClose: () => void;
}

/**
 * Modal para resolver transações marcadas como reembolso mas sem Nota vinculada.
 * Permite: (1) vincular a nota draft existente, (2) criar nova nota e vincular,
 * (3) desmarcar a transação como reembolso (volta a ser despesa normal).
 */
export function LinkReimbursementNoteModal({ transactionId, defaultEmployeeName = "", onClose }: Props) {
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const [selectedNoteId, setSelectedNoteId] = useState("");
  const [showNewNote, setShowNewNote] = useState(false);
  const [newEmployeeName, setNewEmployeeName] = useState(defaultEmployeeName);

  // Draft notes — preferring same employee name first
  const { data: draftNotes = [] } = useQuery({
    queryKey: ["reimbursement-notes-draft-link", defaultEmployeeName],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("reimbursement_notes")
        .select("id, code, employee_name, total_amount")
        .eq("status", "draft")
        .order("created_at", { ascending: false });
      if (error) throw error;
      const list = data || [];
      // Sort: same employee first
      return list.sort((a: any, b: any) => {
        const aMatch = a.employee_name === defaultEmployeeName ? 0 : 1;
        const bMatch = b.employee_name === defaultEmployeeName ? 0 : 1;
        return aMatch - bMatch;
      });
    },
  });

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ["transaction_reimbursement_link", transactionId] });
    queryClient.invalidateQueries({ queryKey: ["transaction_reimbursement_flag", transactionId] });
    queryClient.invalidateQueries({ queryKey: ["transactions"] });
    queryClient.invalidateQueries({ queryKey: ["reimbursement-notes"] });
  };

  const linkMutation = useMutation({
    mutationFn: async (noteId: string) => {
      // Get tx amount + employee
      const { data: tx, error: txErr } = await supabase
        .from("transactions")
        .select("amount, reimbursement_to")
        .eq("id", transactionId)
        .single();
      if (txErr) throw txErr;

      // Get note employee for sync
      const { data: note, error: noteErr } = await supabase
        .from("reimbursement_notes")
        .select("employee_name")
        .eq("id", noteId)
        .single();
      if (noteErr) throw noteErr;

      // Insert link
      const { error: insErr } = await supabase
        .from("reimbursement_note_items")
        .insert({ reimbursement_note_id: noteId, transaction_id: transactionId });
      if (insErr) throw insErr;

      // Sync reimbursement_to to note's employee name
      if (tx.reimbursement_to !== note.employee_name) {
        await supabase
          .from("transactions")
          .update({ reimbursement_to: note.employee_name })
          .eq("id", transactionId);
      }

      // Recalc note total
      const { data: items } = await supabase
        .from("reimbursement_note_items")
        .select("transactions(amount)")
        .eq("reimbursement_note_id", noteId);
      const total = (items || []).reduce((s: number, i: any) => s + Number(i.transactions?.amount || 0), 0);
      await supabase.from("reimbursement_notes").update({ total_amount: total }).eq("id", noteId);
    },
    onSuccess: () => {
      invalidate();
      toast({ title: "Transação vinculada à Nota de Reembolso" });
      onClose();
    },
    onError: (err: any) => toast({ title: "Erro ao vincular", description: err.message, variant: "destructive" }),
  });

  const createAndLinkMutation = useMutation({
    mutationFn: async (employeeName: string) => {
      // Create note (code is auto-generated by trigger)
      const { data: note, error: noteErr } = await supabase
        .from("reimbursement_notes")
        .insert({
          code: "TEMP",
          employee_name: employeeName,
          status: "draft",
          created_by: user?.email || "system",
        } as any)
        .select("id")
        .single();
      if (noteErr) throw noteErr;

      // Insert link
      const { error: insErr } = await supabase
        .from("reimbursement_note_items")
        .insert({ reimbursement_note_id: note.id, transaction_id: transactionId });
      if (insErr) throw insErr;

      // Sync employee name on tx
      await supabase
        .from("transactions")
        .update({ reimbursement_to: employeeName })
        .eq("id", transactionId);

      // Recalc total
      const { data: tx } = await supabase.from("transactions").select("amount").eq("id", transactionId).single();
      await supabase.from("reimbursement_notes").update({ total_amount: Number(tx?.amount || 0) }).eq("id", note.id);
    },
    onSuccess: () => {
      invalidate();
      toast({ title: "Nota de Reembolso criada e vinculada" });
      onClose();
    },
    onError: (err: any) => toast({ title: "Erro ao criar nota", description: err.message, variant: "destructive" }),
  });

  const unmarkMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase
        .from("transactions")
        .update({ is_reimbursement: false, reimbursement_to: null })
        .eq("id", transactionId);
      if (error) throw error;
    },
    onSuccess: () => {
      invalidate();
      toast({ title: "Transação desmarcada como reembolso" });
      onClose();
    },
    onError: (err: any) => toast({ title: "Erro ao desmarcar", description: err.message, variant: "destructive" }),
  });

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Resolver Reembolso sem Nota</DialogTitle>
          <DialogDescription>
            Esta transação está marcada como reembolso, mas não está vinculada a nenhuma Nota.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Vincular nota existente */}
          {!showNewNote && (
            <div className="space-y-2">
              <label className="text-xs font-medium text-muted-foreground">Vincular a Nota existente (rascunho)</label>
              {draftNotes.length === 0 ? (
                <p className="text-xs text-muted-foreground italic">Nenhuma Nota em rascunho disponível.</p>
              ) : (
                <SearchableSelect
                  options={draftNotes.map((n: any) => ({
                    value: n.id,
                    label: `${n.code} — ${n.employee_name}`,
                  }))}
                  value={selectedNoteId}
                  onValueChange={setSelectedNoteId}
                  placeholder="Selecionar nota…"
                  searchPlaceholder="Pesquisar por código ou colaborador…"
                />
              )}
              <Button
                size="sm"
                onClick={() => linkMutation.mutate(selectedNoteId)}
                disabled={!selectedNoteId || linkMutation.isPending}
                className="w-full"
              >
                <Link2 className="mr-1.5 h-3.5 w-3.5" />
                {linkMutation.isPending ? "A vincular…" : "Vincular a Nota selecionada"}
              </Button>
              <button
                type="button"
                onClick={() => setShowNewNote(true)}
                className="flex items-center gap-1 text-xs text-primary hover:underline"
              >
                <Plus className="h-3 w-3" /> Criar nova Nota e vincular
              </button>
            </div>
          )}

          {/* Criar nova nota */}
          {showNewNote && (
            <div className="space-y-2">
              <label className="text-xs font-medium text-muted-foreground">Nome do colaborador</label>
              <Input
                value={newEmployeeName}
                onChange={(e) => setNewEmployeeName(e.target.value)}
                placeholder="Ex.: João Silva"
                autoFocus
              />
              <div className="flex gap-2">
                <Button
                  size="sm"
                  onClick={() => createAndLinkMutation.mutate(newEmployeeName.trim())}
                  disabled={!newEmployeeName.trim() || createAndLinkMutation.isPending}
                  className="flex-1"
                >
                  {createAndLinkMutation.isPending ? "A criar…" : "Criar e vincular"}
                </Button>
                <Button size="sm" variant="ghost" onClick={() => setShowNewNote(false)}>
                  Voltar
                </Button>
              </div>
            </div>
          )}

          <Separator />

          {/* Desmarcar */}
          <div className="space-y-2">
            <label className="text-xs font-medium text-muted-foreground">Ou tratar como despesa normal</label>
            <Button
              size="sm"
              variant="outline"
              onClick={() => unmarkMutation.mutate()}
              disabled={unmarkMutation.isPending}
              className="w-full"
            >
              <Unlink className="mr-1.5 h-3.5 w-3.5" />
              {unmarkMutation.isPending ? "A desmarcar…" : "Desmarcar como Reembolso"}
            </Button>
            <p className="text-[11px] text-muted-foreground">
              A transação manterá o restante (fornecedor, categoria, evento) e poderá ser paga individualmente.
            </p>
          </div>
        </div>

        <div className="flex justify-end pt-2">
          <Button variant="ghost" onClick={onClose}>Cancelar</Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
